-- BCrypt(12) hash of "Admin@1234" — generated by Spring BCryptPasswordEncoder
-- Apply this to all seeded users so they can log in with Admin@1234
UPDATE users
SET password = '$2a$12$IuWdiPlhq2Vd2d1VM629HeJYVpgar.I8yHL.Va619YV9SSk/oTGpG'
WHERE username IN ('admin','analyst','operator','alice','bob','diana','charlie');

-- Remove the temp user we used to generate the hash
DELETE FROM users WHERE username = 'tempuser';
