export const ROLES = { ADMIN: 'ADMIN', ANALYST: 'ANALYST', OPERATOR: 'OPERATOR' }

export const JOB_STATUSES = ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL']

export const SOURCE_TYPES = ['CSV', 'REST_API', 'DATABASE']

export const SOURCE_STATUSES = ['ACTIVE', 'INACTIVE', 'ERROR']

export const TRANSFORMATION_TYPES = [
  'DIRECT_MAPPING', 'UPPERCASE', 'LOWERCASE', 'TRIM',
  'CONCAT', 'DEFAULT_VALUE', 'DATE_FORMAT',
]

export const API_BASE = '/api/v1'
